### ISSUE TITLE
Assume sys_id when no fields are given

### ISSUE THREAD

**Issue by chelming** [thisnameissoclever/ServiceNow-EfficientGlideRecord#1]
# Problem
When I just need to check the existence of a record with `hasNext()` I don't really need any fields returned. Without adding any field, superfluously, I will get an error that "No fields were specified to retrieve."

# Possible solution
When there's no `.addField()` specified, assume that the `sys_id` should be returned. I believe this is how GlideQuery works.

**Comment by thisnameissoclever** [comment]
Thank you for the suggestion, @chelming; When no field is specified, I will indeed have it automatically return the sys_id... and maybe the display value of the record itself? And maybe have `.getDisplayValue()`, when called with no arguments, return the record's display value. 

However, I think the warning in the console (which I believe is just a warning and not an error, right?) is a useful one for someone transitioning from using client-side GlideRecord to EfficientGlideRecord. 
EGR is meant to be a neeeearly drop-in replacement for GR, with the _main_ difference being that you have to specify the fields you want. Therefore, a developer might do a complete drop-in replacement without any additional changes (if they haven't read the documentation thoroughly). In this case, they would find that no fields are available in the callback, and they may be quite confused. This warning is meant to alert the admin of the expected behavior of the API, without preventing them from using it in this way if they'd like (such as in the case you mentioned where they only need to check if a record exists). 

I'm curious what you think. Is the warning too verbose? Too foreboding? I think it's worth keeping in, but if you suggest a change to the wording or an alternative method of elucidating this "_potential_ bug" in the developer's client-side code, I'd be curious to hear your thoughts. For example, do you think it'd be worth changing the message to add something like... 

> "If you only want to check whether a record exists and don't need any fields, you can ignore this message (but be sure to use `.setLimit(1)`). 
> If you want this message to go away, you can use .addField('sys_id') which will not alter the behavior or performance of EfficientGlideRecord"

---

Changes I'll plan based on this issue: 

### In the client-side UI Script: 
1. Update the .query() method to - AFTER the warning is logged - add the sys_id field. 
2. Update the `.getDisplayValue()` method so that if no argument (field name) is specified, the display value of the record itself is returned as a string instead. 
3. Potentially update the warning message that's shown when no fields are specified to include a more helpful message to the developer building the client-side script (curious to hear your feedback on this first though). 

### In the server-side Script Include:
1. Update the server-side code to also return the display value of the record itself in all cases. 
2. Update the server-side code so that even if no fields are specified (which shouldn't be possible unless the user modifies the client-side UI Script(s), but I like to cover my ass), the sys_id will be returned as a field anyway.

**Comment by chelming** [comment]
>However, I think the warning in the console (which I believe is just a warning and not an error, right?) is a useful one for someone transitioning from using client-side GlideRecord to EfficientGlideRecord.

I agree. I think the console.log is fine. Counter point to that I guess is that the user will also get the warning if they .getValue() on a field they haven't .addValue()'d'. There's also jslog but I find that I don't always remember to look there when debugging 😬

**Comment by thisnameissoclever** [comment]
This is now completed in [v1.0.4](https://github.com/thisnameissoclever/ServiceNow-EfficientGlideRecord/releases/tag/v1.0.4), along with support for dot-walking!
